apiVersion: v1
kind: development
metadata:
  name: aspnetapp-pod
  labels:
    name: aspnetapp
spec:
  imagePullSecrets:
    - name: acr-secret
  containers:
    - name: aspnetapp-container
      image: acr101.azurecr.io/sept101image:160
      imagePullPolicy: Always
      resources: 
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-service
spec:
  type: LoadBalancer
  selector:
    name: aspnetapp # Ensure this matches spec.template.metadata.labels in your deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Try 8080 if the app listens on the default non-root .NET port   
