apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp-pod
  labels:
    name: aspnetapp
spec:
  imagePullSecrets:
    - name: acr-secret
  containers:
    - name: aspnetapp-container
      image: shtk8s.azurecr.io/aspnetappks:73
      imagePullPolicy: Always
      resources: 
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-service
spec:
  selector:
    name: aspnetapp
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer   
